version: '3'

volumes:
  test_data_dir:
      driver: local      
services:
  test-postgres:
      image: postgres:latest
      volumes:
        - test_data_dir:/var/lib/postgresql/data
        - ./scripts/:/docker-entrypoint-initdb.d/
      environment:
        POSTGRES_DB: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - 5432:5432
        
        
        
        

